import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import companyRoutes from "./company.routes";
import orderRoutes from "./order.routes";
import deliverymanRoutes from "./deliveryman.routes";
import paymentRoutes from "./payment.routes";
import notificationRoutes from "./notification.routes";
import categoryRoutes from "./category.routes";
import productRoutes from "./product.routes";
import cartRoutes from "./cart.routes";
import bannerRoutes from "./banner.routes";
import uploadRoutes from "./upload.routes";
import settingsRoutes from "./settings.routes";
import reviewRoutes from "./review.routes";
import branchRoutes from "./branch.routes";
import stockItemRoutes from "./stockItem.routes";
import stockBatchRoutes from "./stockBatch.routes";
import stockMovementRoutes from "./stockMovement.routes";
import driverRoutes from "./driver.routes";
import bookingRoutes from "./booking.routes";
import walletRoutes from "./wallet.routes";
import messageRoutes from "./message.routes";
import promoRoutes from "./promo.routes";
import financeRoutes from "./finance.routes";
import helpdeskRoutes from "./helpdesk.routes";
import faqRoutes from "./faq.routes";
import appRoutes from "./app.routes";
import marketingRoutes from "./marketing.routes";
import emailRoutes from "./email.routes";
import preRegisterRoutes from "./preRegister.routes";
import toolsRoutes from "./tools.routes";
import cashbackRoutes from "./cashback.routes";
import couponRoutes from "./coupon.routes";
import packingRoutes from "./packing.routes";
import shopperRoutes from "./shopper.routes";
import franchiseRoutes from "./franchise.routes";
import personRoutes from "./person.routes";
import deliveryAddressRoutes from "./delivery-address.routes";
import guestRoutes from "./guest.routes";
import looseDeliveryRoutes from "./loose-delivery.routes";
import monitorRoutes from "./monitor.routes";
import aclRoutes from "./acl.routes";
import accessGroupRoutes from "./access-group.routes";
import accessGroupSettingsRoutes from "./access-group-settings.routes";
import accessFlowRoutes from "./access-flow.routes";
import groupRoutes from "./group.routes";
import notificationTopicRoutes from "./notification-topic.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/companies", companyRoutes);
router.use("/orders", orderRoutes);
router.use("/deliverymen", deliverymanRoutes);
router.use("/payments", paymentRoutes);
router.use("/notifications", notificationRoutes);
router.use("/categories", categoryRoutes);
router.use("/products", productRoutes);
router.use("/cart", cartRoutes);
router.use("/banners", bannerRoutes);
router.use("/upload", uploadRoutes);
router.use("/settings", settingsRoutes);
router.use("/reviews", reviewRoutes);
router.use("/branches", branchRoutes);
router.use("/stock-items", stockItemRoutes);
router.use("/stock-batches", stockBatchRoutes);
router.use("/stock-movements", stockMovementRoutes);
router.use("/drivers", driverRoutes);
router.use("/bookings", bookingRoutes);
router.use("/wallet", walletRoutes);
router.use("/messages", messageRoutes);
router.use("/promo", promoRoutes);
router.use("/finance", financeRoutes);
router.use("/helpdesk", helpdeskRoutes);
router.use("/faq", faqRoutes);
router.use("/application", appRoutes);
router.use("/marketing", marketingRoutes);
router.use("/emails", emailRoutes);
router.use("/pre-register", preRegisterRoutes);
router.use("/tools", toolsRoutes);
router.use("/cashback", cashbackRoutes);
router.use("/coupon", couponRoutes);
router.use("/packing", packingRoutes);
router.use("/shopper", shopperRoutes);
router.use("/franchises", franchiseRoutes);
router.use("/person", personRoutes);
router.use("/delivery-address", deliveryAddressRoutes);
router.use("/guest", guestRoutes);
router.use("/loose-delivery", looseDeliveryRoutes);
router.use("/monitor", monitorRoutes);
router.use("/acl", aclRoutes);
router.use("/access-group", accessGroupRoutes);
router.use("/settings", accessGroupSettingsRoutes);
router.use("/report/access-flow", accessFlowRoutes);
router.use("/group", groupRoutes);
router.use("/v2/notification-topic", notificationTopicRoutes);

export default router;
