import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import companyRoutes from "./company.routes";
import orderRoutes from "./order.routes";
import deliverymanRoutes from "./deliveryman.routes";
import paymentRoutes from "./payment.routes";
import notificationRoutes from "./notification.routes";
import categoryRoutes from "./category.routes";
import productRoutes from "./product.routes";
import cartRoutes from "./cart.routes";
import bannerRoutes from "./banner.routes";
import uploadRoutes from "./upload.routes";
import settingsRoutes from "./settings.routes";
import reviewRoutes from "./review.routes";
import branchRoutes from "./branch.routes";
import stockItemRoutes from "./stockItem.routes";
import stockBatchRoutes from "./stockBatch.routes";
import stockMovementRoutes from "./stockMovement.routes";
import driverRoutes from "./driver.routes";
import bookingRoutes from "./booking.routes";
import walletRoutes from "./wallet.routes";
import messageRoutes from "./message.routes";
import promoRoutes from "./promo.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/companies", companyRoutes);
router.use("/orders", orderRoutes);
router.use("/deliverymen", deliverymanRoutes);
router.use("/payments", paymentRoutes);
router.use("/notifications", notificationRoutes);
router.use("/categories", categoryRoutes);
router.use("/products", productRoutes);
router.use("/cart", cartRoutes);
router.use("/banners", bannerRoutes);
router.use("/upload", uploadRoutes);
router.use("/settings", settingsRoutes);
router.use("/reviews", reviewRoutes);
router.use("/branches", branchRoutes);
router.use("/stock-items", stockItemRoutes);
router.use("/stock-batches", stockBatchRoutes);
router.use("/stock-movements", stockMovementRoutes);
router.use("/drivers", driverRoutes);
router.use("/bookings", bookingRoutes);
router.use("/wallet", walletRoutes);
router.use("/messages", messageRoutes);
router.use("/promo", promoRoutes);

export default router;
