import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import companyRoutes from "./company.routes";
import orderRoutes from "./order.routes";
import deliverymanRoutes from "./deliveryman.routes";
import paymentRoutes from "./payment.routes";
import notificationRoutes from "./notification.routes";
import categoryRoutes from "./category.routes";
import productRoutes from "./product.routes";
import cartRoutes from "./cart.routes";
import bannerRoutes from "./banner.routes";
import uploadRoutes from "./upload.routes";
import settingsRoutes from "./settings.routes";
import reviewRoutes from "./review.routes";
import branchRoutes from "./branch.routes";
import stockItemRoutes from "./stockItem.routes";
import stockBatchRoutes from "./stockBatch.routes";
import stockMovementRoutes from "./stockMovement.routes";
import driverRoutes from "./driver.routes";
import bookingRoutes from "./booking.routes";
import walletRoutes from "./wallet.routes";
import messageRoutes from "./message.routes";
import promoRoutes from "./promo.routes";
import financeRoutes from "./finance.routes";
import helpdeskRoutes from "./helpdesk.routes";
import faqRoutes from "./faq.routes";
import appRoutes from "./app.routes";
import marketingRoutes from "./marketing.routes";
import emailRoutes from "./email.routes";
import preRegisterRoutes from "./preRegister.routes";
import toolsRoutes from "./tools.routes";
import cashbackRoutes from "./cashback.routes";
import couponRoutes from "./coupon.routes";
import packingRoutes from "./packing.routes";
import shopperRoutes from "./shopper.routes";
import franchiseRoutes from "./franchise.routes";
import personRoutes from "./person.routes";
import deliveryAddressRoutes from "./delivery-address.routes";
import guestRoutes from "./guest.routes";
import looseDeliveryRoutes from "./loose-delivery.routes";
import monitorRoutes from "./monitor.routes";
import aclRoutes from "./acl.routes";
import accessGroupRoutes from "./access-group.routes";
import accessGroupSettingsRoutes from "./access-group-settings.routes";
import accessFlowRoutes from "./access-flow.routes";
import groupRoutes from "./group.routes";
import notificationTopicRoutes from "./notification-topic.routes";
import domainSettingsRoutes from "./domain-settings.routes";
import v2SettingRoutes from "./v2-setting.routes";
import globalSettingsRoutes from "./global-settings.routes";
import accessoriesRoutes from "./accessories.routes";
import foodProductComplementRoutes from "./food-product-complement.routes";
import alertProductRoutes from "./alert-product.routes";
import chatMessageRoutes from "./chat-message.routes";
import frontChatRoutes from "./front-chat.routes";
import deliveryDispatchRoutes from "./delivery-dispatch.routes";
import registerDeliverymanRoutes from "./register-deliveryman.routes";
import searchRoutes from "./search.routes";
import sliderRoutes from "./slider.routes";
import tabloidRoutes from "./tabloid.routes";
import tipRoutes from "./tip.routes";
import tipDeliverymanRoutes from "./tip-deliveryman.routes";
import siteRoutes from "./site.routes";
import logRoutes from "./log.routes";
import mobilityCrudRoutes from "./mobility-crud.routes";
import mobilityAppRoutes from "./mobility-app.routes";
import mobilityServicePassengerRoutes from "./mobility-service-passenger.routes";
import mobilityExtrasRoutes from "./mobility-extras.routes";
import mobilityReportExtraRoutes from "./mobility-report-extra.routes";
import mapsRoutes from "./maps.routes";
import voucherRoutes from "./voucher.routes";
import walletV2Routes from "./wallet-v2.routes";
import ecbrImageBankRoutes from "./ecbr-image-bank.routes";
import imageBankRoutes from "./image-bank.routes";
import addressRoutes from "./address.routes";
import publicCompanyRoutes from "./public-company.routes";
import twilioRoutes from "./twilio.routes";
import { authenticate } from "../middleware/auth";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/companies", companyRoutes);
router.use("/orders", orderRoutes);
router.use("/deliverymen", deliverymanRoutes);
router.use("/payments", paymentRoutes);
router.use("/notifications", notificationRoutes);
router.use("/categories", categoryRoutes);
router.use("/products", productRoutes);
router.use("/cart", cartRoutes);
router.use("/banners", bannerRoutes);
router.use("/upload", uploadRoutes);
router.use("/settings", settingsRoutes);
router.use("/reviews", reviewRoutes);
router.use("/branches", branchRoutes);
router.use("/stock-items", stockItemRoutes);
router.use("/stock-batches", stockBatchRoutes);
router.use("/stock-movements", stockMovementRoutes);
router.use("/drivers", driverRoutes);
router.use("/bookings", bookingRoutes);
router.use("/wallet", walletRoutes);
router.use("/messages", messageRoutes);
router.use("/promo", promoRoutes);
router.use("/finance", financeRoutes);
router.use("/helpdesk", helpdeskRoutes);
router.use("/faq", faqRoutes);
router.use("/application", appRoutes);
router.use("/marketing", marketingRoutes);
router.use("/emails", emailRoutes);
router.use("/pre-register", preRegisterRoutes);
router.use("/tools", toolsRoutes);
router.use("/cashback", cashbackRoutes);
router.use("/coupon", couponRoutes);
router.use("/packing", packingRoutes);
router.use("/shopper", shopperRoutes);
router.use("/franchises", franchiseRoutes);
router.use("/person", personRoutes);
router.use("/delivery-address", deliveryAddressRoutes);
router.use("/guest", guestRoutes);
router.use("/loose-delivery", looseDeliveryRoutes);
router.use("/monitor", monitorRoutes);
router.use("/acl", aclRoutes);
router.use("/access-group", accessGroupRoutes);
router.use("/settings", accessGroupSettingsRoutes);
router.use("/report/access-flow", accessFlowRoutes);
router.use("/group", groupRoutes);
router.use("/v2/notification-topic", notificationTopicRoutes);
router.use("/setting", domainSettingsRoutes);
router.use("/v2/setting", v2SettingRoutes);
router.use("/global/settings", globalSettingsRoutes);
router.use("/v2/accessories", accessoriesRoutes);
router.use("/food/product-complement", foodProductComplementRoutes);
router.use("/v2/customer-alert-product", authenticate, alertProductRoutes);
router.use("/chat", authenticate, chatMessageRoutes);
router.use("/v1/front/chat", authenticate, frontChatRoutes);
router.use("/deliveryMan", authenticate, deliveryDispatchRoutes);
router.use("/delivery-man", authenticate, deliveryDispatchRoutes);
router.use("/register-deliveryman", authenticate, registerDeliverymanRoutes);
router.use("/v1/search", authenticate, searchRoutes);
router.use("/slider", authenticate, sliderRoutes);
router.use("/tabloid", authenticate, tabloidRoutes);
router.use("/Tip", authenticate, tipRoutes);
router.use("/TipDeliveryMan", authenticate, tipDeliverymanRoutes);
router.use("/company/site", authenticate, siteRoutes);
router.use("/log", authenticate, logRoutes);
router.use("/v1/mobility", mobilityReportExtraRoutes);
router.use("/v1/mobility", mobilityCrudRoutes);
router.use("/v1/mobility", mobilityAppRoutes);
router.use("/v1/mobility", mobilityServicePassengerRoutes);
router.use("/v1/mobility", mobilityExtrasRoutes);
router.use("/v1/mobility/maps", mapsRoutes);
router.use("/v2/vouchers", authenticate, voucherRoutes);
router.use("/v2/wallet", authenticate, walletV2Routes);
router.use("/v2/ecbr-image-bank", authenticate, ecbrImageBankRoutes);
router.use("/imageBank", imageBankRoutes);
router.use("/v2/address", addressRoutes);
router.use("/v2/company", publicCompanyRoutes);
router.use("/twilio", twilioRoutes);

export default router;
