const url = window.location.host;

export class MenuConfig {
	public defaults: any = {
		header: {
			self: {},
			items: [
				{
					title: "Dashboards",
					root: true,
					alignment: "left",
					page: "/dashboard",
					translate: "MENU.DASHBOARD",
				},
			],
		},
		aside: {
			self: {},
			items: [
				{
					section: "Empresa",
					translate: "GLOBAL.LABEL.COMPANY",
				},
				{
					title: "Dashboard",
					root: true,
					icon: "flaticon2-architecture-and-city",
					page: "/dashboard",
					permission: ["accessToGlobal"],
					translate: "MENU.DASHBOARD",
					bullet: "dot",
				},

				{
					title: "Franquias",
					translate: "GLOBAL.LABEL.FRANCHISES",
					root: true,
					bullet: "dot",
					permission: ["accessToRoot"],
					page: "/franchises/",
					icon: "flaticon2-layers",
				},
				{
					title: "Empresa",
					translate: "GLOBAL.LABEL.COMPANY",
					root: true,
					bullet: "dot",
					permission: [
						"accessToGlobal",
						"accessToCompanyGroup",
						"accessToCompanyCompany",
						"accessToCompanyDelivery",
						"accessToHoursCompany",
						"accessToCouponsCoupon",
						"accessToCompanySegment",
					],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Grupo",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/company/group",
							permission: ["accessToGlobal", "accessToCompanyGroup"],
							translate: "MENU.COMPANY.GROUP",
							bullet: "dot",
						},
						{
							title: "Empresa",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/company/company",
							permission: ["accessToGlobal", "accessToCompanyCompany"],
							translate: "GLOBAL.LABEL.COMPANY",
							bullet: "dot",
						},
						{
							title: "Delivery",
							root: true,
							icon: "flaticon-truck",
							page: "/company/delivery",
							permission: ["accessToGlobal", "accessToCompanyDelivery"],
							translate: "GLOBAL.LABEL.COMPANYDELIVERY",
							bullet: "dot",
						},
						{
							title: "Segmentos",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/company/segment",
							permission: ["accessToGlobal", "accessToCompanySegment"],
							translate: "GLOBAL.LABEL.COMPANY",
							bullet: "dot",
						},
						{
							title: "Horário funcionamento",
							root: true,
							icon: "flaticon2-calendar-4",
							page: "/company/opening-hours",
							permission: ["accessToHoursCompany"],
							translate: "MENU.SETTINGS.CONTROLLER",
							bullet: "dot",
						},
						{
							title: "Cupons",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/company/coupon",
							permission: ["accessToGlobal", "accessToCouponsCoupon"],
							translate: "GLOBAL.LABEL.COUPONS",
							bullet: "dot",
						},
					],
				},
				{
					title: "Ferramentas",
					translate: "GLOBAL.LABEL.TOOLS",
					root: true,
					bullet: "dot",
					permission: [
						"accessToGlobal",
						"accessToToolsNotifications",
						"accessToEstablishmentSlider",
						"accessToToolsPopup",
						"accessToIntegrations",
					],
					icon: "flaticon2-browser-2",
					submenu: [
						// {
						// 	title: "Notificação",
						// 	root: true,
						// 	icon: "flaticon2-bell-2",
						// 	page: "/tools-notifications",
						// 	permission: ["accessToGlobal", "accessToToolsNotifications"],
						// 	translate: "MENU.TOOLS.NOTIFICATION",
						// 	bullet: "dot",
						// },
						{
							title: "Integrações",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/tools/integrations",
							permission: ["accessToGlobal", "accessToIntegrations"],
							translate: "MENU.TOOLS.INTEGRATIONS",
							bullet: "dot",
						},
						{
							title: "Slider",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/establishment-slider",
							permission: ["accessToGlobal", "accessToEstablishmentSlider"],
							translate: "MENU.TOOLS.SLIDER",
							bullet: "dot",
						},
						// {
						// 	title: "Topico Notificação",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	page: "/topic-notification",
						// 	permission: ["accessToGlobal", "accessToTopicNotification"],
						// 	translate: "Topico Notificações",
						// 	bullet: "dot",
						// },
						{
							title: "Notificação",
							root: true,
							icon: "flaticon2-notification",
							page: "/custom-notification",
							permission: ["accessToGlobal"],
							translate: "Notificações",
							bullet: "dot",
						},
					],
				},
				{
					title: "Help Desk",
					translate: "GLOBAL.LABEL.HELPDESK",
					root: true,
					bullet: "dot",
					permission: ["accessToGlobal", "accessToHelpDeskTickets"],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Tickets",
							root: true,
							icon: "flaticon2-architecture-and-city",
							translate: "MENU.HELPDESK.TICKETS",
							permission: ["accessToGlobal", "accessToHelpDeskTickets"],
							page: "/helpdesk/tickets",
							bullet: "dot",
						},
					],
				},
				{
					title: "Serviços",
					translate: "GLOBAL.LABEL.RESTAURANTSONLINE",
					root: true,
					bullet: "dot",
					permission: ["accessToGlobal", "accessToFoodMenu", "accessToFoodOrders"],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Pedidos",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/shopping-cart/restaurant",
							permission: ["accessToGlobal", "accessToFoodOrders"],
							translate: "MENU.RESTAURANTSONLINE.REQUESTS",
							bullet: "dot",
						},
						{
							title: "Produtos",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/delivery-products",
							permission: ["accessToGlobal", "accessToFoodMenu"],
							translate: "MENU.RESTAURANTSONLINE.MENU",
							bullet: "dot",
						},
					],
				},
				// {
				// 	title: "Acessórios Online",
				// 	translate: "GLOBAL.LABEL.ACCESSORIESONLINE",
				// 	root: true,
				// 	bullet: "dot",
				// 	permission: [
				// 		"accessToGlobal",
				// 		"accessToAccessoriesMenu",
				// 		"accessToAccessoriesOrders",
				// 	],
				// 	icon: "flaticon2-browser-2",
				// 	submenu: [
				// 		{
				// 			title: "Pedidos",
				// 			root: true,
				// 			icon: "flaticon2-architecture-and-city",
				// 			page: "/shopping-cart/accessories",
				// 			permission: ["accessToGlobal", "accessToAccessoriesOrders"],
				// 			translate: "MENU.ACCESSORIESONLINE.REQUESTS",
				// 			bullet: "dot",
				// 		},
				// 		{
				// 			title: "Produtos",
				// 			root: true,
				// 			icon: "flaticon2-architecture-and-city",
				// 			page: "/accessories-menu",
				// 			permission: ["accessToGlobal", "accessToAccessoriesMenu"],
				// 			translate: "MENU.ACCESSORIESONLINE.MENU",
				// 			bullet: "dot",
				// 		},
				// 	],
				// },
				{
					title: "Supermercado Online",
					translate: "GLOBAL.LABEL.SUPERMARKETONLINE",
					root: true,
					bullet: "dot",
					permission: [
						"accessToGlobal",
						"accessToRegisterProduct",
						"accessToPaymentmethos",
						"accessToMarketIntegrations",
						"accessToMarketOrders",
					],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Pedidos",
							root: true,
							icon: "flaticon2-architecture-and-city",
							translate: "MENU.SUPERMARKETONLINE.REQUESTS",
							page: "/shopping-cart/supermarket",
							permission: ["accessToGlobal", "accessToMarketOrders"],
							bullet: "dot",
						},
						{
							title: "Produto",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/product",
							permission: ["accessToGlobal", "accessToRegisterProduct"],
							translate: "MENU.SUPERMARKETONLINE.PRODUCT",
							bullet: "dot",
						},
						{
							title: "Métodos de pagamento",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/supermarketonline-paymentmethods",
							permission: ["accessToGlobal", "accessToPaymentmethos"],
							translate: "MENU.SUPERMARKETONLINE.PAYMENTMETHODS",
							bullet: "dot",
						},
						{
							title: "Integrações",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/supermarketonline/integrations",
							permission: ["accessToGlobal", "accessToMarketIntegrations"],
							translate: "MENU.SUPERMARKETONLINE.INTEGRATIONS",
							bullet: "dot",
						},
					],
				},
				{
					title: "Aplicativo",
					translate: "GLOBAL.LABEL.APPLICATION",
					root: true,
					bullet: "dot",
					permission: ["accessToGlobal", "accessToApplicationCategory", "accessToToolsPopup"],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Categoria",
							root: true,
							icon: "flaticon2-architecture-and-city",
							translate: "MENU.APPLICATION.CATEGORY",
							permission: ["accessToGlobal", "accessToApplicationCategory"],
							page: "/app/category",
							bullet: "dot",
						},
						// {
						// 	title: "Popup",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	page: "/app/popup",
						// 	permission: ["accessToGlobal", "accessToToolsPopup"],
						// 	translate: "MENU.APPLICATION.POPUP",
						// 	bullet: "dot",
						// },
					],
				},
				{
					title: "Configurações",
					translate: "GLOBAL.LABEL.SETTINGS",
					root: true,
					bullet: "dot",
					permission: [
						"accessToGlobal",
						"accessToSettingsCity",
						"accessToSettingsTypesUsers",
						"accessToPackingPacking",
						"accessToAclModule",
						"accessToSettingsController",
					],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Versões do Aplicativo",
							root: true,
							icon: "flaticon-rocket",
							page: "/app-versions",
							permission: ["accessToRoot"],
							bullet: "dot",
						},
						{
							title: "Tipos de e-mail",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/emails/types",
							permission: ["accessToRoot"],
							translate: "MENU.SETTINGS.EMAILTYPES",
							bullet: "dot",
						},
						{
							title: "Templates de e-mail",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/emails/templates",
							permission: ["accessToGlobal", "accessToSettingsEmailTemplates"],
							translate: "MENU.SETTINGS.EMAILTEMPLATES",
							bullet: "dot",
						},
						{
							title: "Gerais",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/general-settings",
							permission: ["accessToFranchises"],
							translate: "Gerais",
							bullet: "dot",
						},
						{
							title: "Cidade",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/settings-city",
							permission: ["accessToRoot"],
							translate: "MENU.SETTINGS.CITY",
							bullet: "dot",
						},
						// {
						// 	title: "Tipos de usuários",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	page: "/settings-types-users",
						// 	permission: ["accessToGlobal", "accessToSettingsTypesUsers"],
						// 	translate: "MENU.SETTINGS.TYPESUSERS",
						// 	bullet: "dot",
						// },
						{
							title: "Embalagem",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/packing-packing",
							permission: ["accessToGlobal", "accessToPackingPacking"],
							translate: "MENU.SETTINGS.PACKING",
							bullet: "dot",
						},
						// {
						// 	title: "Módulos",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	page: "/acl-module",
						// 	permission: ["accessToGlobal", "accessToAclModule"],
						// 	translate: "MENU.ACL.MODULE",
						// 	bullet: "dot",
						// },
						// {
						// 	title: "Controlador",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	page: "/settings-controller",
						// 	permission: ["accessToGlobal", "accessToSettingsController"],
						// 	translate: "MENU.SETTINGS.CONTROLLER",
						// 	bullet: "dot",
						// },
					],
				},
				{
					title: "Cadastros",
					translate: "GLOBAL.LABEL.REGISTER",
					root: true,
					bullet: "dot",
					permission: [
						"accessToGlobal",
						"accessToDeliveryRecord",
						"accessToShopperShopper",
						"accessToUserUser",
						"accessToPersonPerson",
						"accessToDepartmentDepartment",
						"accessToRegisterProduct",
					],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Entregadores",
							root: true,
							icon: "flaticon-truck",
							page: "/delivery-deliveryrecord",
							permission: ["accessToGlobal", "accessToDeliveryRecord"],
							translate: "MENU.REGISTER.COURIERS",
							bullet: "dot",
						},
						{
							title: "Shoppers",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/shopper-shopper",
							permission: ["accessToGlobal", "accessToShopperShopper"],
							translate: "MENU.REGISTER.SHOPPERS",
							bullet: "dot",
						},
						{
							title: "Usuários",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/user-user",
							permission: ["accessToGlobal", "accessToUserUser"],
							// translate: 'MENU.SETTINGS.USERS',
							bullet: "dot",
						},
						{
							title: "Pessoa",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/person-person",
							permission: ["accessToGlobal", "accessToPersonPerson"],
							translate: "MENU.REGISTER.PERSON",
							bullet: "dot",
						},
						{
							title: "Departamento",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/department-department",
							permission: [
								"accessToGlobal",
								"accessToDepartmentDepartment",
								"accessToRegisterProduct",
							],
							translate: "MENU.REGISTER.DEPARTMENT",
							bullet: "dot",
						},
					],
				},
				{
					title: "Admin",
					translate: "GLOBAL.LABEL.ADMIN",
					root: true,
					bullet: "dot",
					permission: [
						"accessToGlobal",
						"accessToAclRoles",
						"accessToSupportNoc",
						"accessToAclPermissions",
						"accessToManagementImageBank",
						"accessToLogsLog",
						"accessToAccessGroup",
						"accessToProductsBank",
					],
					icon: "flaticon2-browser-2",
					submenu: [
						// {
						// 	title: "Papéis",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	page: "/adm/roles",
						// 	permission: ["accessToGlobal", "accessToAclRoles"],
						// 	translate: "MENU.ADMIN.ROLES",
						// 	bullet: "dot",
						// },
						{
							title: "Banco de produtos",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/adm/products-bank",
							permission: ["accessToGlobal", "accessToProductsBank"],
							translate: "MENU.ADMIN.PRODUCTBANK",
							bullet: "dot",
						},
						{
							title: "Noc",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/adm/noc",
							permission: ["accessToGlobal", "accessToSupportNoc"],
							translate: "MENU.ADMIN.NOC",
							bullet: "dot",
						},
						// {
						// 	title: "Permissões",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	page: "/adm/permissions",
						// 	permission: ["accessToGlobal", "accessToAclPermissions"],
						// 	translate: "MENU.ADMIN.PERMISSIONS",
						// 	bullet: "dot",
						// },
						{
							title: "Banco de imagens",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/management-imagebank",
							permission: ["accessToGlobal", "accessToManagementImageBank"],
							translate: "MENU.ADMIN.IMAGEBANK",
							bullet: "dot",
						},
						{
							title: "Histórico",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/logs-log",
							permission: ["accessToGlobal", "accessToLogsLog"],
							translate: "MENU.ADMIN.LOG",
							bullet: "dot",
						},
						// {
						// 	title: "Access Group",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	page: "/accessgroup-accessGroup",
						// 	permission: ["accessToGlobal", "accessToAccessGroup"],
						// 	translate: "MENU.ADMIN.ACCESSGROUP",
						// 	bullet: "dot",
						// },
					],
				},
				{
					title: "Suporte",
					translate: "GLOBAL.LABEL.SUPPORT",
					root: true,
					bullet: "dot",
					permission: [
						"accessToGlobal",
						"accessToAclRoles",
						"accessToSupportNoc",
						"accessToAclPermissions",
						"accessToManagementImageBank",
						"accessToLogsLog",
						"accessToAccessGroup",
						"accessToFaq",
						"accessToBugOrders",
					],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Carrinho",
							root: true,
							icon: "flaticon-cart",
							page: "/support/shopping-cart",
							permission: ["accessToGlobal", "accessToAclRoles"],
							translate: "MENU.ADMIN.ROLES",
							bullet: "dot",
						},
						{
							title: "FAQ",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/helpdesk/faq",
							permission: ["accessToGlobal", "accessToFaq"],
							translate: "MENU.SUPPORT.FAQ",
							bullet: "dot",
						},
						{
							title: "Compras com bug",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/support/bug-orders",
							permission: ["accessToGlobal", "accessToBugOrders"],
							translate: "MENU.SUPPORT.BUGGYSHOPPING",
							bullet: "dot",
						},
					],
				},
				{
					title: "Relatórios",
					translate: "GLOBAL.LABEL.REPORTS",
					root: true,
					bullet: "dot",
					permission: [
						"accessToGlobal",
						"accessToReportsCustomer",
						"accessToReportsPartners",
						"accessToReportsmanMaps",
						"accessToReportsFavoriteProducts",
						"accessToReportsAccessFlow",
						"accessToReportFinance",
					],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Pedidos Cancelados",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/report/canceled-orders",
							permission: ["accessToGlobal"],
							translate: "Pedidos Cancelados",
							bullet: "dot",
						},
						{
							title: "Financeiro",
							icon: "flaticon2-architecture-and-city",
							root: true,
							page: "/report/adm/financial",
							permission: ["accessToRoot"],
							translate: "MENU.REPORTS.CUSTOMER",
							bullet: "dot",
						},
						{
							title: "Financeiro Franquia",
							icon: "flaticon2-architecture-and-city",
							root: true,
							page: "/report/financial",
							permission: ["accessToFranchises"],
							translate: "MENU.REPORTS.CUSTOMER",
							bullet: "dot",
						},
						{
							title: "Financeiro Empresa",
							icon: "flaticon2-architecture-and-city",
							root: true,
							page: "/report/financial-company",
							permission: ["accessToReportFinance"],
							translate: "MENU.REPORTS.CUSTOMER",
							bullet: "dot",
						},
						{
							title: "Entregas",
							icon: "flaticon2-architecture-and-city",
							root: true,
							page: "/report/deliveries",
							permission: ["accessToGlobal", "accessToFranchises"],
							translate: "Entregas",
							bullet: "dot",
						},
						{
							title: "Clientes",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/report/customer",
							permission: ["accessToGlobal", "accessToReportsCustomer"],
							translate: "MENU.REPORTS.CUSTOMER",
							bullet: "dot",
						},
						{
							title: "Parceiros",
							root: true,
							icon: "flaticon2-architecture-and-city",
							page: "/report/partners",
							permission: ["accessToGlobal", "accessToReportsPartners"],
							translate: "MENU.REPORTS.CUSTOMER",
							bullet: "dot",
						},
						{
							title: "Mapa Deliveryman",
							root: true,
							icon: "flaticon2-map",
							page: "/report/deliverymanlive",
							permission: ["accessToGlobal", "accessToReportsmanMaps"],
							translate: "GLOBAL.LABEL.LIVE",
							bullet: "dot",
						},
						// {
						// 	title: "Produtos Favoritados",
						// 	root: true,
						// 	icon: "flaticon2-map",
						// 	page: "/report/favorite-products",
						// 	permission: ["accessToGlobal", "accessToReportsFavoriteProducts"],
						// 	translate: "MENU.REPORTS.FAVORITEPRODUCTS",
						// 	bullet: "dot",
						// },
						// {
						// 	title: "Fluxo de acessos",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	page: "/report/access-flow",
						// 	permission: ["accessToGlobal", "accessToReportsAccessFlow"],
						// 	translate: "MENU.REPORTS.ACCESSFLOW",
						// 	bullet: "dot",
						// },
					],
				},
				// {
				// 	title: "Marketing",
				// 	translate: "GLOBAL.LABEL.MARKETING",
				// 	root: true,
				// 	bullet: "dot",
				// 	permission: ["accessToGlobal", "accessToCampanha"],
				// 	icon: "flaticon2-browser-2",
				// 	submenu: [
				// 		{
				// 			title: "Campanha",
				// 			root: true,
				// 			icon: "flaticon2-architecture-and-city",
				// 			page: "/marketing/campaign",
				// 			permission: ["accessToGlobal", "accessToCampanha"],
				// 			translate: "MENU.MARKETING.CAMPAIGN",
				// 			bullet: "dot",
				// 		},
				// 	],
				// },

				{
					section: "Financeiro",
					translate: "GLOBAL.LABEL.FINANCE",
				},
				{
					title: "Financeiro",
					translate: "GLOBAL.LABEL.FINANCIAL",
					root: true,
					bullet: "dot",
					permission: [
						"accessToGlobal",
						"accessToTypePayments",
						// "accessToSubordinates",
						"accessToTransactions",
						"accessToTransactionsBraspag",
					],
					icon: "flaticon2-browser-2",
					submenu: [
						{
							title: "Vouchers",
							root: true,
							icon: "flaticon2-gift",
							translate: "Vouchers",
							permission: ["accessToGlobal"],
							page: "/finance/vouchers",
							bullet: "dot",
						},
						{
							title: "Centros de Custo",
							root: true,
							icon: "flaticon2-architecture-and-city",
							translate: "MENU.FINANCIAL.COSTCENTERS",
							permission: ["accessToGlobal", "accessToCostCenter"],
							page: "/finance/cost-centers",
							bullet: "dot",
						},
						{
							title: "Tipos de pagamento",
							root: true,
							icon: "flaticon2-architecture-and-city",
							translate: "MENU.FINANCIAL.TYPEPAYMENTS",
							permission: ["accessToGlobal", "accessToTypePayments"],
							page: "/finance/type-payments",
							bullet: "dot",
						},
						// {
						// 	title: "Subordinado",
						// 	root: true,
						// 	icon: "flaticon2-architecture-and-city",
						// 	translate: "MENU.FINANCIAL.SUBORDINATE",
						// 	permission: ["accessToGlobal", "accessToSubordinates"],
						// 	page: "/finance/braspag/subordinates",
						// 	bullet: "dot",
						// },
						{
							title: "Transações",
							root: true,
							icon: "flaticon2-architecture-and-city",
							translate: "MENU.FINANCIAL.TYPEPAYMENTS",
							permission: ["accessToGlobal", "accessToTransactions"],
							page: "/finance/invoice",
							bullet: "dot",
						},
						{
							title: "Transações Braspag",
							root: true,
							icon: "flaticon2-architecture-and-city",
							translate: "MENU.FINANCIAL.TRANSACTIONSBRASPAG",
							permission: ["accessToGlobal", "accessToTransactionsBraspag"],
							page: "/finance/braspag/transactions",
							bullet: "dot",
						},
					],
				},
				{
					title: "Contas Digitais",
					translate: "GLOBAL.LABEL.DIGIALACCOUNTS",
					root: true,
					bullet: "dot",
					permission: [
						"accessToRoot",
						"accessToGlobal",
						"accessToTypePayments",
						// "accessToSubordinates",
						"accessToTransactions",
						"accessToTransactionsBraspag",
					],
					icon: "flaticon-piggy-bank",
					submenu: [
						{
							title: "Banco",
							root: true,
							icon: "flaticon-security",
							translate: "MENU.FINANCIAL.BANK",
							permission: ["accessToRoot"],
							page: "/finance/digital-accounts/banks",
							bullet: "dot",
						},
						{
							title: "Agências",
							root: true,
							icon: "flaticon2-shelter",
							translate: "MENU.FINANCIAL.AGENCY",
							permission: ["accessToRoot"],
							page: "/finance/digital-accounts/agencies",
							bullet: "dot",
						},
						{
							title: "Contas Bancárias",
							root: true,
							icon: "flaticon2-avatar",
							translate: "MENU.FINANCIAL.ACCOUNT",
							permission: ["accessToGlobal", "accessToRoot"],
							page: "/finance/digital-accounts/accounts",
							bullet: "dot",
						},
						{
							title: "Extrato Bancário",
							root: true,
							icon: "flaticon2-paper",
							translate: "MENU.FINANCIAL.EXTRACT",
							permission: ["accessToGlobal", "accessToRoot", "accessToTransactions"],
							page: "/finance/digital-accounts/extract",
							bullet: "dot",
						},
					],
				},
				{
					title: "Cashback",
					translate: "GLOBAL.LABEL.CASHBACK",
					root: true,
					bullet: "dot",
					permission: ["accessToGlobal"],
					icon: "flaticon2-refresh",
					submenu: [
						{
							title: "Campanhas",
							root: true,
							icon: "flaticon2-start-up",
							translate: "MENU.CASHBACK.CAMPAIGN",
							permission: ["accessToGlobal"],
							page: "/cashbask/campaigns",
							bullet: "dot",
						},
						{
							title: "Histórico",
							root: true,
							icon: "flaticon2-list-2",
							translate: "MENU.CASHBACK.CAMPAIGN",
							permission: ["accessToGlobal"],
							page: "/cashbask/histories",
							bullet: "dot",
						},
					],
				},
			],
		},
	};

	constructor() {
		// Menu Mobility disable in Production
		// if (url !== "admin.toopdelivery.com.br") {
		this.defaults.aside.items.push({
			section: "Mobilidade Urbana",
			translate: "GLOBAL.LABEL.MOBILITY",
		});

		this.defaults.aside.items.push({
			title: "Cadastros",
			translate: "GLOBAL.LABEL.REGISTER",
			root: true,
			bullet: "dot",
			permission: [
				"accessToGlobal",
				"accessMobilityToPassengers",
				"accessMobilityToDrivers",
				"accessMobilityToServices",
				"accessMobilityToNotifications",
				"accessMobilityToSlider",
			],
			icon: "flaticon-folder",
			submenu: [
				{
					title: "Passageiros",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/passengers",
					permission: ["accessToGlobal", "accessMobilityToPassengers"],
					translate: "MENU.REGISTER.PASSENGERS",
					bullet: "dot",
				},

				{
					title: "Motoristas",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/drivers",
					permission: ["accessToGlobal", "accessMobilityToDrivers"],
					translate: "MENU.REGISTER.DRIVERS",
					bullet: "dot",
				},

				{
					title: "Serviços",
					translate: "GLOBAL.LABEL.SERVICES",
					root: true,
					bullet: "dot",
					permission: ["accessToGlobal", "accessMobilityToServices"],
					page: "/mobility/services/",
					icon: "flaticon2-rocket-1",
				},
				{
					title: "Slider",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/slider",
					permission: ["accessToGlobal", "accessMobilityToSlider"],
					translate: "MENU.REGISTER.SLIDER",
					bullet: "dot",
				},
				{
					title: "Push Notificações",
					translate: "GLOBAL.LABEL.NOTIFICATIONS",
					root: true,
					bullet: "dot",
					permission: ["accessToGlobal", "accessMobilityToNotifications"],
					page: "/mobility/push-notifications",
					icon: "flaticon2-bell-2",
				},
				{
					title: "Veículos",
					translate: "Veículos",
					root: true,
					bullet: "dot",
					permission: ["accessToGlobal"],
					page: "/mobility/vehicle",
					icon: "flaticon-edit-1",
				},
				{
					title: "Cupom Desconto",
					translate: "Cupom Desconto",
					root: true,
					bullet: "dot",
					permission: ["accessToRoot", "accessToGlobal", "discountCoupon"],
					page: "/mobility/discount",
					icon: "flaticon-edit-1",
				},
				{
					title: "Agendamentos",
					translate: "MENU.REGISTER.SCHEDULE",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/schedule",
					permission: ["accessToRoot", "accessToGlobal"],
					bullet: "dot",
				},
			],
		});

		this.defaults.aside.items.push({
			title: "Aprovações",
			root: true,
			bullet: "dot",
			permission: ["accessToGlobal", "accessToRoot", "accessToDeliveryRecord", "accessToDrivers"],
			icon: "flaticon-eye",
			submenu: [
				{
					title: "Motoristas",
					root: true,
					icon: "flaticon-network",
					page: "/approval-drivers",
					permission: [
						"accessToGlobal",
						"accessToRoot",
						"accessToDeliveryRecord",
						"accessToDrivers",
					],
					bullet: "dot",
				},
			],
		});

		this.defaults.aside.items.push({
			title: "Parametros",
			translate: "GLOBAL.LABEL.PARAMETERS",
			root: true,
			bullet: "dot",
			permission: [
				"accessToGlobal",
				"accessMobilityToSubject",
				"accessMobilityToDocumentsTypes",
				"accessMobilityToPeakHours",
			],
			icon: "flaticon2-settings",
			submenu: [
				{
					title: "Assuntos/Motivos",
					root: true,
					icon: "flaticon2-paper",
					page: "/mobility/parameters-subjects",
					permission: ["accessToGlobal", "accessMobilityToSubject"],
					translate: "GLOBAL.LABEL.SUBJECT",
					bullet: "dot",
				},
				{
					title: "Tipos de Documentos",
					root: true,
					icon: "flaticon2-document",
					page: "/mobility/parameters-documenttypes",
					permission: ["accessToGlobal", "accessMobilityToDocumentsTypes"],
					translate: "GLOBAL.LABEL.DOCUMENTTYPES",
					bullet: "dot",
				},
				{
					title: "Horários de Pico",
					root: true,
					icon: "flaticon2-calendar-1",
					page: "/mobility/parameters-peakhours",
					permission: ["accessToGlobal", "accessMobilityToPeakHours"],
					translate: "GLOBAL.LABEL.PEAKHOURS",
					bullet: "dot",
				},
			],
		});

		this.defaults.aside.items.push({
			title: "Avaliações",
			translate: "Avaliações",
			root: true,
			bullet: "dot",
			permission: ["accessToGlobal", "accessMobilityToPassengers", "accessMobilityToServices"],
			icon: "flaticon-folder",
			submenu: [
				{
					title: "Avaliação Passageiros",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/evaluation/passenger",
					permission: ["accessToGlobal", "accessMobilityToPassengers"],
					translate: "Avaliação Passageiros",
					bullet: "dot",
				},
				{
					title: "Avaliação Motorista",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/evaluation/driver",
					permission: ["accessToGlobal", "accessMobilityToPassengers"],
					translate: "Avaliação Motorista",
					bullet: "dot",
				},
			],
		});

		this.defaults.aside.items.push({
			title: "Configurações",
			translate: "GLOBAL.LABEL.SETTINGS",
			root: true,
			bullet: "dot",
			permission: ["accessToGlobal", "accessToFranchises"],
			icon: "flaticon-folder",
			submenu: [
				{
					title: "Geral",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/settings/general",
					permission: ["accessToRoot", "accessToGlobal", "accessToFranchises"],
					translate: "GLOBAL.LABEL.GENERAL",
					bullet: "dot",
				},
			],
		});

		this.defaults.aside.items.push({
			title: "Mapa",
			translate: "Mapa",
			root: true,
			bullet: "dot",
			permission: ["accessToGlobal"],
			icon: "flaticon-folder",
			submenu: [
				{
					title: "Monitoramento",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/map/monitoring",
					permission: ["accessToGlobal", "accessMobilityToPassengers"],
					translate: "GLOBAL.LABEL.MONITORING",
					bullet: "dot",
				},
				{
					title: "Mapa Geral",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/map/general",
					permission: ["accessToGlobal", "accessMobilityToPassengers"],
					translate: "Mapa Geral",
					bullet: "dot",
				},
				{
					title: "Mapa Calor",
					root: true,
					icon: "flaticon2-map",
					page: "/mobility/map/heatmap",
					permission: ["accessToGlobal"],
					translate: "Mapa Calor",
					bullet: "dot",
				},
			],
		});

		this.defaults.aside.items.push({
			title: "Relatórios",
			translate: "GLOBAL.LABEL.REPORTS",
			root: true,
			bullet: "dot",
			permission: ["accessToGlobal"],
			icon: "flaticon-folder",
			submenu: [
				{
					title: "Receitas viagens",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/report/adm/driver",
					permission: ["accessToGlobal", "accessMobilityToPassengers"],
					translate: "GLOBAL.LABEL.TRAVELRECIPES",
					bullet: "dot",
				},
				{
					title: "Receitas Passageiros",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/report/passenger",
					permission: ["accessToGlobal", "accessMobilityToPassengers"],
					translate: "GLOBAL.LABEL.PASSENGERRECEIPTS",
					bullet: "dot",
				},
				{
					title: "Motorista",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/report/driver",
					permission: ["accessToGlobal", "accessMobilityToDriver"],
					translate: "GLOBAL.LABEL.DRIVER",
					bullet: "dot",
				},
				{
					title: "Viagens",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/report/races",
					permission: ["accessToGlobal", "accessMobilityToPassengers"],
					translate: "GLOBAL.LABEL.TRIPS",
					bullet: "dot",
				},
				{
					title: "Logs",
					root: true,
					icon: "flaticon2-reload",
					page: "/mobility/report/logs",
					permission: ["accessToGlobal", "accessToRoot", "accessToReportLogs"],
					translate: "GLOBAL.LABEL.LOG",
					bullet: "dot",
				},
			],
		});
		// }
	}

	public get configs(): any {
		return this.defaults;
	}
}

new MenuConfig().defaults.aside = {};
