export const GET_USER_SAGA = 'GET_USER_SAGA';
export const SET_USER_SAGA = 'SET_USER_SAGA';
export const CLEAN_USER_SAGA = 'CLEAN_USER_SAGA';

export const GET_BOOKING_SAGA = 'GET_BOOKING_SAGA';
export const SET_BOOKING_SAGA = 'SET_BOOKING_SAGA';
export const UPDATE_BOOKING_SAGA = 'UPDATE_BOOKING_SAGA';
export const CLEAN_BOOKING_SAGA = 'CLEAN_BOOKING_SAGA';

export const GET_LOCATION_SAGA = 'GET_LOCATION_SAGA';
export const SET_LOCATION_SAGA = 'SET_LOCATION_SAGA';

export const SET_MESSAGE_SAGA = 'SET_MESSAGE_SAGA';

export const SET_CONFIGURATION_SAGA = 'SET_CONFIGURATION_SAGA';
