export const nextStatus = [
  'WAIT_COMPANY',
  'IN_PREPARATION',
  'WAIT_DELIVERYMAN',
  'ACCEPT_DELIVERYMAN',
  'DELIVERY_ROUTE',
];

export const companyStatus = [
  'WAIT_COMPANY',
  'IN_PREPARATION',
  'WAIT_DELIVERYMAN',
];

export const deliveryStatus = [
  'WAIT_DELIVERYMAN',
  'ACCEPT_DELIVERYMAN',
  'DISPATCH',
  'DELIVERY_ROUTE',
];

export const humanReadableStatus = {
  ACCEPT_DELIVERYMAN: 'MOTOBOY A CAMINHO',
  CANCELED: 'CANCELADO',
  DELIVERY_ROUTE: 'A CAMINHO DO CLIENTE',
  FINISHED: 'ENTREGUE',
  IN_PREPARATION: 'EM PREPARAÇÃO',
  RELEASE_SHOPPER: 'PEDIDO A CAMINHO',
  WAIT_COMPANY: 'NOVO PEDIDO',
  WAIT_DELIVERYMAN: 'AGUARDANDO MOTOBOY',
  DISPATCH: 'PEDIDO A CAMINHO',
};
