export const GET_USER_SAGA = 'GET_USER_SAGA';
export const SET_USER_SAGA = 'SET_USER_SAGA';
export const CLEAN_USER_SAGA = 'CLEAN_USER_SAGA';
export const SET_UPDATE_ORDER = 'SET_UPDATE_ORDER';

export const SET_LOCATION_SAGA = 'SET_LOCATION_SAGA';
export const GET_LOCATION_SAGA = 'GET_LOCATION_SAGA';
export const CLEAN_LOCATION_SAGA = 'CLEAN_LOCATION_SAGA';

export const SET_PIP_ANDROID_UPDATE = 'SET_PIP_ANDROID_UPDATE';
